MOOCS:
    - Prof. Gilbert Strang (Math LA)
    - Prof. Dennis Auroux (Math MVC)
    - Prof. Walter Lewin (Physics EM, Mechanics)
    - Prof. Andrew Ng (CS ML)
    
USC:
        - Prof. Bhaskar Krishnamachari (EECS)
        - Prof. Guillermo Reyes Souto (MATH)
        - Prof. Neelesh Tiruviluamala (MATH)
        - Prof. Spencer Gerhardt (MATH)
        - Prof. Stephen Tu (EE)
        - Prof. Remigijus Mikulevicius (MATH)
        - Prof. Robert Guralnick (MATH)
        - Prof. Gary Rosen (MATH)
        - Prof. Vatsal Sharan (CS)
        - Prof. Prof. Satish Kumar Thittamaranahalli (CS/PHY)
        - John Gunnar Carlsson (ISE) 
        
IISc:
        - Prof. P. Vijay Kumar
        - Prof. Rajesh Sundaresan 
        - Prof. Bharadwaj Amrutur
        - Tarun (Sir) Chaubisa

NITR:        
        - Prof. Debiprasad P Acharya
        - Prof. Sunil Kumar Sarangi
        - Prof. K Subhasini
        - Prof. Dipti Patra
        - Prof. Paresh Kale
        - Prof. Pankaj Sa
        - Prof. P.K Sahu
        - Prof. Bidyadhar Subidhi
        - Amiya Kumar Samantaray
        - Balmiki Sir


"Higher Secondary School":
        - Abhay Sir (Vidwan)
        - Chhatrapati Sir (College of Basic Science and Humanities, OUAT)
        - Jyoti Tripathi (Vidwan)
        - Karunakar Patra (Naidu)
        - Dinesh Das
        - Alok Bal (Naidu)
        - Naidu Sir (Naidu)
        

"Secondary School":
    - Ratnakar Sir 
    - Niharika (Das) Pattnaik 
    - Pushpanjali Singh (Science, KV Balasore)
    - Pratibha Sahoo (Maths, KV Balasore)
    - Jena Ma'am (Science, KV Balasore)
    - Patra Sir (KV Balasore)
    - Raghunath Sir (Vidyaniketan)
    - Bidyadhar Sir (Vidyaniketan)
    - Sanatan Sir (Vidyaniketan)
    - Amit Sir (Babanka office sanga)


"Primary School":
    - Ms. Mary Martin (RPS, Angul)
    - Trupti Ma'am (RPS Angul)
    - Pavitra Sir (Science/Maths)
    - Anita Das (RPS Angul)
